/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
 
const awsmobile = {
 "aws_project_region": "eu-west-1",
 "aws_cognito_region": "eu-west-1",
 "aws_user_pools_id": "eu-west-1_beL7oQctG",
 "aws_user_pools_web_client_id": "4f0dfp36q75fvtedep4rm859dj",
 "oauth": {
    "domain": "joblimain.auth.eu-west-1.amazoncognito.com",
 }
};
 
export default awsmobile;