/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
 
const awsmobile = {
 "aws_project_region": "us-east-1",
 "aws_cognito_region": "us-east-1",
 "aws_user_pools_id": "us-east-1_wrxS5vVkt",
 "aws_user_pools_web_client_id": "7bupg3qvnjjr0ck3u8e9ksnn0d",
 "oauth": {
 "domain": "joblimain.auth.us-east-1.amazoncognito.com",
 }
};
 
export default awsmobile;